const CLOUD_NAME='dlizw7yxk';const UPLOAD_PRESET='armain_unsigned';
const loginScreen=document.getElementById('login-screen');const adminPanel=document.getElementById('admin-panel');
document.getElementById('toggle')?.addEventListener('click',()=>{password.type=password.type==='password'?'text':'password'});
loginForm.addEventListener('submit',e=>{e.preventDefault();auth.signInWithEmailAndPassword(email.value,password.value).catch(err=>alert('Error: '+err.message))});
logout.onclick=()=>auth.signOut();
auth.onAuthStateChanged(u=>{if(u){loginScreen.style.display='none';adminPanel.style.display='flex';cargarTab('slides')}else{loginScreen.style.display='flex';adminPanel.style.display='none'}});
function cargarTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const c=tabContent;
if(tab==='slides'){c.innerHTML=`<div class="card-admin"><h2>Slides</h2><input type="file" id="sf" accept="image/*"><button class="primary" id="ss">Subir</button><div id="sl" class="list"></div></div>`;ss.onclick=async()=>{const f=sf.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);fd.append('upload_preset',UPLOAD_PRESET);const r=await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/upload`,{method:'POST',body:fd});const d=await r.json();if(d.error)return alert('Cloudinary: crea preset UNSIGNED');await db.collection('slides').add({url:d.secure_url,orden:Date.now()})};db.collection('slides').onSnapshot(s=>sl.innerHTML=s.docs.map(x=>`<div class="item"><img src="${x.data().url}"><button class="del-x" onclick="db.collection('slides').doc('${x.id}').delete()">×</button></div>`).join(''))}
if(tab==='categorias'){c.innerHTML=`<div class="card-admin"><h2>Categorías</h2><div class="grid-2"><input id="cn" placeholder="Nombre"><input id="cd" placeholder="Descripción"></div><button class="primary" id="ac">Guardar</button><div id="cl" class="list"></div></div>`;ac.onclick=()=>{db.collection('categorias').add({nombre:cn.value,descripcion:cd.value});cn.value='';cd.value=''};db.collection('categorias').onSnapshot(s=>cl.innerHTML=s.docs.map(x=>`<div class="item">${x.data().nombre}<button class="del-x" onclick="db.collection('categorias').doc('${x.id}').delete()">×</button></div>`).join(''))}
if(tab==='productos'){c.innerHTML=`<div class="card-admin"><h2>Productos</h2><div class="grid-2"><input id="pn" placeholder="Nombre"><input id="pm" placeholder="Marca"><input id="pp" type="number" placeholder="Precio ARS"><select id="pc"></select></div><textarea id="pd" placeholder="Descripción"></textarea><input type="file" id="pf"><button class="primary" id="ap">Guardar</button><button class="primary" id="up" style="display:none;background:#b8955a">Actualizar</button><div id="pl" class="list"></div></div>`;let edit=null;db.collection('categorias').get().then(s=>pc.innerHTML=s.docs.map(x=>`<option value="${x.id}">${x.data().nombre}</option>`).join(''));ap.onclick=async()=>{const f=pf.files[0];if(!f)return alert('Imagen requerida');const fd=new FormData();fd.append('file',f);fd.append('upload_preset',UPLOAD_PRESET);const r=await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/upload`,{method:'POST',body:fd});const d=await r.json();await db.collection('productos').add({nombre:pn.value,marca:pm.value,precio:Number(pp.value),categoria:pc.value,descripcion:pd.value,imagen:d.secure_url,creado:Date.now()});pn.value=pm.value=pp.value=pd.value=''};up.onclick=async()=>{const data={nombre:pn.value,marca:pm.value,precio:Number(pp.value),categoria:pc.value,descripcion:pd.value};const f=pf.files[0];if(f){const fd=new FormData();fd.append('file',f);fd.append('upload_preset',UPLOAD_PRESET);const r=await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/upload`,{method:'POST',body:fd});const d=await r.json();data.imagen=d.secure_url}await db.collection('productos').doc(edit).update(data);edit=null;ap.style.display='inline-block';up.style.display='none'};db.collection('productos').onSnapshot(s=>pl.innerHTML=s.docs.map(x=>{const p=x.data();return`<div class="item"><button class="del-x" onclick="if(confirm('¿Eliminar?'))db.collection('productos').doc('${x.id}').delete()">×</button><img src="${p.imagen}"><strong>${p.nombre}</strong><br>$${p.precio}<br><button onclick="editar('${x.id}')">Editar</button></div>`}).join(''));window.editar=async id=>{const d=await db.collection('productos').doc(id).get();const p=d.data();pn.value=p.nombre;pm.value=p.marca||'';pp.value=p.precio;pc.value=p.categoria;pd.value=p.descripcion||'';edit=id;ap.style.display='none';up.style.display='inline-block';scrollTo(0,0)}}
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>cargarTab(b.dataset.tab));
